### ISSUE TITLE
How do I add Java to the service catalog?

### ISSUE THREAD

**Issue by ryannix123** [openshift-evangelists/Wild-West-Frontend#7]
I would love to run this demo. However, java isn't in the default OKD service catalog.

**Comment by danielhelfand** [comment]
@ryannix123 Hey, this is long overdue, but you can run the following to add a Java component to your service catalog: 

```
curl -kL https://gist.github.com/jorgemoralespou/033c27a354406d7c5111711346e79b01/raw 2> /dev/null | oc apply -n openshift --as system:admin -f -
```

Just make sure you are logged in with `oc`.

**Comment by ryannix123** [comment]
Yes, it works! Thanks, @danielhelfand !
